### PR TITLE
public_send for removed methods javascript_importmap_shim_nonce_configuration_tag

### PR DESCRIPTION
**Pull request by moskvin**
& javascript_importmap_shim_tag

### CODE REVIEW

**Comment by Halphas** [comment]
plis merrrge :D :(

**Comment by mshibuya** [comment]
What problem is this change trying to address?

**Comment by moskvin** [comment]
I was trying resolve issue when I got a crash error about javascript_importmap_shim_nonce_configuration_tag is not found from Rails (7.1.3) + importmap-rails (2.0.1) and rails_admin (3.1.2). ref #3666 (Support importmap-rails 2.0 - 24380d53f7c82eef4758e96a0b98e9d4333a806d)

**Comment by mshibuya** [comment]
Sorry but I don't understand, why https://github.com/railsadminteam/rails_admin/commit/24380d53f7c82eef4758e96a0b98e9d4333a806d doesn't work?

**Comment by Halphas** [comment]
I'm too new in ruby to understand this but i when I updated rails from 7.1.2 to 7.1.3 hit went sideways :D, when i applied this code in the sources i could access but on my deployment systems obviously im building packages from their respective repos and wont be editing sources :x pls merge pls

**Comment by moskvin** [comment]
> Sorry but I don't understand, why [24380d5](https://github.com/railsadminteam/rails_admin/commit/24380d53f7c82eef4758e96a0b98e9d4333a806d) doesn't work?

What should I provide to you to explain more the problem? Should I provide a project example with the crash?

**Comment by mshibuya** [comment]
https://github.com/railsadminteam/rails_admin/commit/24380d53f7c82eef4758e96a0b98e9d4333a806d is the fix which should have **already** addressed https://github.com/railsadminteam/rails_admin/discussions/3666. So if you're saying you have the another issue that wasn't fixed by https://github.com/railsadminteam/rails_admin/commit/24380d53f7c82eef4758e96a0b98e9d4333a806d, you need to provide an example.
Have you already tested with the rails_admin master branch?

**Comment by moskvin** [comment]
> [24380d5](https://github.com/railsadminteam/rails_admin/commit/24380d53f7c82eef4758e96a0b98e9d4333a806d) is the fix which should have **already** addressed #3666. So if you're saying you have the another issue that wasn't fixed by [24380d5](https://github.com/railsadminteam/rails_admin/commit/24380d53f7c82eef4758e96a0b98e9d4333a806d), you need to provide an example. Have you already tested with the rails_admin master branch?

I apologise for the inconvenience, and I appreciate your guidance. It turns out that specifying the development branch indeed resolved the issue, as you suggested.
```
gem 'rails_admin', github: 'railsadminteam/rails_admin', branch: 'master'
```

**Pull request closed without merging**
