### PR TITLE
add not like operator (does not contain)

### PR DESCRIPTION
**Pull request by QPierre1**
We would like to add negative search filters
In reference to https://github.com/railsadminteam/rails_admin/issues/3393

### CODE REVIEW

**Comment by mshibuya** [comment]
Thanks for the implementation, could you add some tests for this?

**Comment by QPierre1** [comment]
I don't manage to run `bundle exec rake spec`.
It returns it cannot load shrine. shrine is installed by the gemfile located in /spec/dummy_app.
Is https://github.com/railsadminteam/rails_admin/blob/2.x-stable/CONTRIBUTING.md the only documentation about contributing ?

**Comment by QPierre1** [comment]
I can't manage to run local tests by following https://github.com/railsadminteam/rails_admin/blob/master/CONTRIBUTING.md#submitting-a-pull-request

I use these commands : 
```
appraisal install
bundle exec appraisal rake test
```

**Comment by codealchemy** [comment]
Please rebase against the latest changes to resolve CI issues (fixed in https://github.com/railsadminteam/rails_admin/commit/a042aeb23b4f6df2d5ba3c2f5b32bdcce3d940b0)

**Comment by QPierre1** [comment]
I add the fix. We already use the v2.x-stable in production and need this feature quickly, is it possible to stay on the 2.x-stable branch, waiting master to be stable ? In that way, we can already use our fork without breaking anything.

**Comment by mshibuya** [comment]
A new feature should go into the master first, then it can be back-ported afterwards. Can you switch target to the master branch?

**Comment by QPierre1** [comment]
Ok I switch to master.
Should I create a specific PR for 2.x-stable ?

**Comment by mshibuya** [comment]
One more step, please resolve Prettier and RuboCop failures 🙏 
https://github.com/railsadminteam/rails_admin/runs/4227675468?check_suite_focus=true
https://github.com/railsadminteam/rails_admin/runs/4227675326?check_suite_focus=true

> Should I create a specific PR for 2.x-stable ?

I'd be glad if you can!

**Comment by mshibuya** [comment]
Thanks for the contribution! 🎉

**Pull request merged**
