### PR TITLE
Allow turbo-rails 2 in gemspec

### PR DESCRIPTION
**Pull request by bb**
See https://github.com/railsadminteam/rails_admin/issues/3661#issuecomment-1927663367

### CODE REVIEW

**Review by pathakh — APPROVED** [review]

**Comment by mshibuya** [comment]
CI is failing, but I can handle it. Thanks!

**Comment by bb** [comment]
Thank you!

**Comment by xijo** [comment]
@pathakh any chance to release this soon-ish? Feels bad to force us all to stay on an outdated version of turbo :|

**Comment by bb** [comment]
@mshibuya thanks for providing the hotfixes 3.1.3+4. Are there any plans to create a new minor release from master (which includes this PR)?

If not, could you please update the patch version in master to 3.1.4 so we can refer to master in our bundle without having to ignore https://github.com/railsadminteam/rails_admin/security/advisories/GHSA-8qgm-g2vv-vwvc in our audits.

**Comment by mshibuya** [comment]
I've just released a pre-release version 3.2.0.beta. The master was also bumped to that version.
It'll take some more time for the next minor release, but please give feedback so it can happen earlier 🙏

**Comment by bb** [comment]
That's great, thank you! I tried it locally and in CI. Also converted an App from Sprockets to Ruby-Vite (thanks to #3643) which also works for me. Good to go, from my perspective. 🚀

**Pull request merged**
