### PR TITLE
restore 2.x config loading behavior

### PR DESCRIPTION
**Pull request by q3aiml**
Attempt to restore 2.x config loading behavior where 1) per-model config blocks
only evaluate after all the models are loaded and associations are defined
while 2) initializer config block evaluates immediately so that routes are
configured correctly.

One remaining change compared to 2.x is RailsAdmin::Config#model no longer
returns the model when given a block. With the removal of LazyModel in e4ae669
it is tricky to both defer initialization and return the model class.

Fixes https://github.com/railsadminteam/rails_admin/issues/3490

### CODE REVIEW

**Comment by mshibuya** [comment]
Thanks for trying! I like your idea, but

> 2) initializer config block evaluates immediately

there's a problem with this part. This will cause the issue with autoloading.

Sorry not covering it in the spec for now, I was unable to reproduce from the spec it since it happens during the initial loading stage. But you can reproduce it by using [the dummy app](https://github.com/railsadminteam/rails_admin/tree/master/spec/dummy_app), with changing [the initializer](https://github.com/railsadminteam/rails_admin/blob/master/spec/dummy_app/config/initializers/rails_admin.rb) as

```diff
 RailsAdmin.config do |c|
   c.asset_source = CI_ASSET
-  c.model 'Team' do
+  c.model Team do
     include_all_fields
     field :color, :color
   end
```

and starting the Rails app. You will get `uninitialized constant Team` error, since the Rails autoloader is not set up yet on the execution of the RailsAdmin initializer. But this notation `c.model <a model class>` is totally valid in the current DSL.
Hence my choice was to defer initialization to some extent...

Could you see if this is fixable?

**Comment by q3aiml** [comment]
Thanks for the review! I didn't think about how that change was intentional with 3.x (unless I am mistaken I think the autoload error exists as well in 2.x when using `c.model <a model class>` in the initializer). After reviewing issues like https://github.com/railsadminteam/rails_admin/issues/3025 I can see how it could be less confusing to defer the initializer config too.

I made a first attempt at a fix. The idea is to have two separate lists of deferred config blocks: one for the initializer config (I called it "core"??) and one for the model config. It probably deserves a little cleanup but I want to get it out for your thoughts before getting too far along. Currently it does change some methods that could be considered public api with the release of 3.0.0 so that might deserve some rework as well.

**Comment by jeromedalbert** [comment]
Thanks for making this PR, I am having class loading issues on staging/production when I use rails_admin 3.0 along with the [makara](https://github.com/instacart/makara) gem, and your PR fixes it by restoring the old 2.x behavior. I hope it gets merged.

**Comment by mshibuya** [comment]
Sorry for not getting back for a long time, I needed some time to consider all implications of the initialization process.
And I came to realize that the change proposed in this PR is not compatible with the Importmap support #3488, which requires `asset_source` to be set earlier than `after_initialize`.

So I'm proposing another way to address this as #3541. It would be great if you could take a look.

**Comment by q3aiml** [comment]
Thanks for circling back with the update! It's definitely a tricky problem. And good catch on the importmap incompatibility.

At first look #3541 makes sense to me. I'll give it a try shortly.

**Pull request closed without merging**
